FROM apache/airflow:2.10.0-python3.10

# Install base dependencies
COPY docker/requirements_airflow.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# Copy code into container (Airflow expects /opt/airflow/*)
COPY airflow /opt/airflow
COPY src /opt/airflow/src
COPY config /opt/airflow/config
